"""update users table

Revision ID: 35cb78e8afd4
Revises: 7e0720fa5043
Create Date: 2019-04-09 20:41:47.366822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35cb78e8afd4'
down_revision = '7e0720fa5043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('key', sa.String(length=150), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.drop_column('users', 'key')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
